INSERT INTO USER (FIRST_NAME, SECOND_NAME, EMAIL, PASSWORD, ROLE)
VALUES ('ADMIN#TEST', 'Sname of Admin#TEST', 'admin#TEST@mail.com', '$2y$12$I7h2fLT5nNPnZRxhnqSOke6LyYqUU2VyCayYyPsuOuTUz8g4.naiS', 'ADMIN');

INSERT INTO USER (FIRST_NAME, SECOND_NAME, EMAIL, PASSWORD, ROLE)
VALUES ('Fname of User#TEST', 'Sname of User#TEST', 'user#TEST@mail.com', '$2y$12$I7h2fLT5nNPnZRxhnqSOke6LyYqUU2VyCayYyPsuOuTUz8g4.naiS', 'USER');

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (3000, 56.0, '2019-11-26', 'LAND', 'This is LAND.....', 2, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (3000, 56.0, '2019-11-26', 'LAND', 'This is LAND.....', 2, TRUE);
