version: '3'
services:
  db:
    container_name: 'mongodb'
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: realties
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    network_mode: 'host'

  backend:
    container_name: 'resource-server'
    image: resource-server
    ports:
      - '8090:8090'
    depends_on:
      - db
       - keycloak
    network_mode: 'host'

  frontend:
    container_name: 'client-server'
    build: './client/'
    ports:
    - '4200:4200'
    depends_on:
      - db
      - backend
      - keycloak
    networks: 
    - project-network

  keycloak:
    container_name: 'auth-server'
    image: jboss/keycloak:8.0.1
    volumes: 
      - ./keycloak:/opt/jboss/keycloak/imports
    environment: 
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports: 
      - '8080:8080'
    command: "-b 0.0.0.0 -Dkeycloak.import=/opt/jboss/keycloak/imports/realm-export.json"
    networks: 
      - project-network

networks:
  project-network: {}
