CREATE TABLE IF NOT EXISTS USER (USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY, FIRST_NAME VARCHAR(60), SECOND_NAME VARCHAR(60), EMAIL VARCHAR(60), PASSWORD VARCHAR(60), ROLE VARCHAR(20));
CREATE TABLE IF NOT EXISTS REALTY (ID BIGINT AUTO_INCREMENT PRIMARY KEY, PRICE DOUBLE, SQUARE DOUBLE, DATE_OF_CREATION DATE, TYPE VARCHAR(60), DESCRIPTION VARCHAR(255), USER_ID BIGINT, IS_DELETED BOOLEAN);
