INSERT INTO USER (FIRST_NAME, SECOND_NAME, EMAIL, PASSWORD, ROLE)
VALUES ('ADMIN#1', 'Sname of Admin#1', 'admin#1@mail.com', '$2y$12$3TzQVKMsVlEN1qOhhOj8KeeuDPZkGe0S.YTHgqI04xEVaIikSuqKe', 'ADMIN');

INSERT INTO USER (FIRST_NAME, SECOND_NAME, EMAIL, PASSWORD, ROLE)
VALUES ('ADMIN#2', 'Sname of Admin#2', 'admin#2@mail.com', '$2y$12$I7h2fLT5nNPnZRxhnqSOke6LyYqUU2VyCayYyPsuOuTUz8g4.naiS', 'ADMIN');

INSERT INTO USER (FIRST_NAME, SECOND_NAME, EMAIL, PASSWORD, ROLE)
VALUES ('Fname of User#3', 'Sname of User#3', 'user#3@mail.com', '$2y$12$I7h2fLT5nNPnZRxhnqSOke6LyYqUU2VyCayYyPsuOuTUz8g4.naiS', 'USER');

INSERT INTO USER (FIRST_NAME, SECOND_NAME, EMAIL, PASSWORD, ROLE)
VALUES ('Fname of User#4', 'Sname of User#4', 'user#4@mail.com', '$2y$12$I7h2fLT5nNPnZRxhnqSOke6LyYqUU2VyCayYyPsuOuTUz8g4.naiS', 'USER');

INSERT INTO USER (FIRST_NAME, SECOND_NAME, EMAIL, PASSWORD, ROLE)
VALUES ('Fname of User#5', 'Sname of User#5', 'user#5@mail.com', '$2y$12$I7h2fLT5nNPnZRxhnqSOke6LyYqUU2VyCayYyPsuOuTUz8g4.naiS', 'USER');

INSERT INTO USER (FIRST_NAME, SECOND_NAME, EMAIL, PASSWORD, ROLE)
VALUES ('Fname of User#6', 'Sname of User#6', 'user#6@mail.com', '$2y$12$I7h2fLT5nNPnZRxhnqSOke6LyYqUU2VyCayYyPsuOuTUz8g4.naiS', 'USER');

INSERT INTO USER (FIRST_NAME, SECOND_NAME, EMAIL, PASSWORD, ROLE)
VALUES ('Fname of User#7', 'Sname of User#7', 'user#7@mail.com', '$2y$12$I7h2fLT5nNPnZRxhnqSOke6LyYqUU2VyCayYyPsuOuTUz8g4.naiS', 'USER');

INSERT INTO USER (FIRST_NAME, SECOND_NAME, EMAIL, PASSWORD, ROLE)
VALUES ('Fname of User#8', 'Sname of User#8', 'user#8@mail.com', '$2y$12$I7h2fLT5nNPnZRxhnqSOke6LyYqUU2VyCayYyPsuOuTUz8g4.naiS', 'USER');

INSERT INTO USER (FIRST_NAME, SECOND_NAME, EMAIL, PASSWORD, ROLE)
VALUES ('Fname of User#9', 'Sname of User#9', 'user#9@mail.com', '$2y$12$I7h2fLT5nNPnZRxhnqSOke6LyYqUU2VyCayYyPsuOuTUz8g4.naiS', 'USER');

INSERT INTO USER (FIRST_NAME, SECOND_NAME, EMAIL, PASSWORD, ROLE)
VALUES ('Fname of User#10', 'Sname of User#10', 'user#10@mail.com', '$2y$12$I7h2fLT5nNPnZRxhnqSOke6LyYqUU2VyCayYyPsuOuTUz8g4.naiS', 'USER');


INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (3000, 56.0, '2019-11-26', 'LAND', 'This is LAND.....', 3, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (6000, 56.0, '2019-11-26', 'LAND', 'This is LAND.....', 4, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (7500, 69.0, '2019-11-26', 'LIVING_ROOM', 'This is LIVING ROOM.....', 4, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (2000, 49.0, '2019-11-26', 'NON_RESIDENTIAL_PREMISES', 'This is NON RESIDENTIAL PREMISES.....', 4, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (560, 35.0, '2019-11-26', 'LIVING_ROOM', 'This is LIVING ROOM.....', 5, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (4500, 40.0, '2019-11-26', 'NON_RESIDENTIAL_PREMISES', 'This is NON RESIDENTIAL PREMISES.....', 6, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (3580, 600.0, '2019-11-26', 'NON_RESIDENTIAL_PREMISES', 'This is NON RESIDENTIAL PREMISES.....', 7, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (12300, 100.0, '2019-11-26', 'LIVING_ROOM', 'This is LIVING ROOM.....', 8, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (400, 10.0, '2019-11-26', 'LAND', 'This is LAND.....', 9, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (1010, 20.0, '2019-11-26', 'LIVING_ROOM', 'This is LIVING ROOM.....', 3, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (1890, 40.0, '2019-11-26', 'LAND', 'This is LAND.....', 3, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (150, 20.0, '2019-11-26', 'LIVING_ROOM', 'This is LIVING ROOM.....', 10, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (4500, 40.0, '2019-11-26', 'NON_RESIDENTIAL_PREMISES', 'This is NON RESIDENTIAL PREMISES.....', 10, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (3580, 600.0, '2019-11-26', 'NON_RESIDENTIAL_PREMISES', 'This is NON RESIDENTIAL PREMISES.....', 10, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (12300, 100.0, '2019-11-26', 'LIVING_ROOM', 'This is LIVING ROOM.....', 5, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (400, 10.0, '2019-11-26', 'LAND', 'This is LAND.....', 6, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (1010, 20.0, '2019-11-26', 'LIVING_ROOM', 'This is LIVING ROOM.....', 7, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (1890, 40.0, '2019-11-26', 'LAND', 'This is LAND.....', 7, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (150, 20.0, '2019-11-26', 'LIVING_ROOM', 'This is LIVING ROOM.....', 8, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (4500, 40.0, '2019-11-26', 'NON_RESIDENTIAL_PREMISES', 'This is NON RESIDENTIAL PREMISES.....', 9, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (3580, 600.0, '2019-11-26', 'NON_RESIDENTIAL_PREMISES', 'This is NON RESIDENTIAL PREMISES.....', 10, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (12300, 100.0, '2019-11-26', 'LIVING_ROOM', 'This is LIVING ROOM.....', 3, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (400, 10.0, '2019-11-26', 'LAND', 'This is LAND.....', 5, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (1010, 20.0, '2019-11-26', 'LIVING_ROOM', 'This is LIVING ROOM.....', 9, FALSE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (1890, 40.0, '2019-11-26', 'LAND', 'This is LAND.....', 10, FALSE);

-- DELETED:
INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (170, 20.0, '2019-11-26', 'LAND', 'This is LAND.....', 8, TRUE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (3450, 45.0, '2019-11-26', 'LIVING_ROOM', 'This is LIVING ROOM.....', 9, TRUE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (1320, 67.0, '2019-11-26', 'LAND', 'This is LAND.....', 10, TRUE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (2340, 36.0, '2019-11-26', 'NON_RESIDENTIAL_PREMISES', 'This is NON RESIDENTIAL PREMISES.....', 5, TRUE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (2340, 34.0, '2019-11-26', 'LIVING_ROOM', 'This is LIVING ROOM.....', 4, TRUE);

INSERT INTO REALTY (PRICE, SQUARE, DATE_OF_CREATION, TYPE, DESCRIPTION, USER_ID, IS_DELETED)
VALUES (6970, 254.0, '2019-11-26', 'NON_RESIDENTIAL_PREMISES', 'This is NON RESIDENTIAL PREMISES.....', 3, TRUE);