server:
  servlet:
    contextPath: /api/v1
spring:
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    driverClassName: org.h2.Driver
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: validate
    show-sql: true
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
  security:
    user:
      name: root
      password: root


message:
  resourceNotFound:
    realty:
      one: Realty not found
      list: Realties not found
    user:
      one: User not found
  noRightsForAction: You haven't rights for this action
  jwtException: Expired or invalid JWT token