global:
    scrape_interval:     5s
    evaluation_interval: 5s
scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/api/v1/actuator/prometheus'
    static_configs:
      - targets: ['localhost:8090']
